### ISSUE TITLE
Please add ability to specify %define statements in rpm spec

### ISSUE THREAD

**Issue by jzarzeckis** [monai/gulp-brass#1]
The template for spec has only 2 %define statements included.
It would be useful to have it possible to specify additional %define statements that would be added conditionally.

**Comment by monai** [comment]
I didn't had time yet to write thorough documentation but it's on high priority. So in this particular case and in general the essential API design goal is sane defaults and extensibility over configuration.

Spec file and service templates are and will be kept at bare minimum. If you want to extend something or add features, you should copy default template and add necessary lines or write your own from scratch.

In your particular case gulpfile section regarding spec task should look like this:

``` js
gulp.task('spec', [ 'files' ], function () {
    return gulp.src('path/to/your/spec/file')
    .pipe(rpm.spec()) // fills piped handlebars template with rpm.options. You can use here any other template engine.
    .pipe(gulp.dest(rpm.buildDir_SPECS));
});
```
