### ISSUE TITLE
Prefix not honored

### ISSUE THREAD

**Issue by arciisine** [monai/gulp-brass#13]
Looking at the options object, there is a prefix parameter that doesn't seem to be used anywhere (cannot find it in the template or the rpm code).  I would like to build a relocatable RPM, and so I assume it would be as simple as just adding the '%prefix' directive and using the variable if specified.

**Comment by monai** [comment]
`options.prefix` is used in [gulp-brass-npm](https://github.com/monai/gulp-brass-npm), and why it is defined in this package and not in the other I don't remember. It may be refactoring leftover. Both these packages and especially example project need throughout review.

For spec file customization see #1: you can copy default spec file template and extend it with anything you want. I want to keep the template as simple as possible.
