### ISSUE TITLE
User/Group Creation

### ISSUE THREAD

**Issue by arciisine** [monai/gulp-brass#14]
Would it be possible to attempt to create the user/group defined in the RPM, if the user/group doesn't exist.  

It would be nice to be able to use the new group/user, and adding in a custom post/pre install script seems like it would be difficult in general.  

I'm thinking it might be a good idea to add a flag to create user/group instead of doing it automatically.

**Comment by monai** [comment]
RPM is OS agnostic packaging system and user/group creation is OS specific task. So common sense suggests to either create a wrapper to cover different OSes or to do nothing and let user to implement user/group creation in their way; again, see #1.

You can spot this kind of bug [here](https://github.com/monai/gulp-brass/blob/develop/assets/rpm/spec#L49). `%systemd_post` is macro present in CentOS and maybe other RHELs but not in OS X. On OS X rpmbuild silently passes without macro expansion and that something is wrong can be seen only during or after RPM installation.

Not strictly related to your question, but I prefer to use RPM only for file (application and systemd unit) management. Every other application asset (user/group, data directory, /etc/myapp.conf, etc.) I define in server provisioning profile (in my case Puppet). This workflow makes RPM packages very simple and server definitions explicit. And yes, this workflow violates all good RPM packaging practices but my concern is to deploy my application on my server, not to distribute the package for third parties.
