### ISSUE TITLE
tar related error thrown when trying to build RPM

### ISSUE THREAD

**Issue by parky128** [monai/gulp-brass#17]
Hi,

I am trying to use create RPM's following the node-simple example, in fact I am using virtually the exact same gulp task code:

```
var path   = require('path');
var gulp   = require('gulp');
var rimraf = require('rimraf');
var npm    = require('gulp-brass-npm');
var brass  = require('gulp-brass');

var pkg, options, rpm;

pkg = require('../package.json');
options = npm.getOptions(pkg);
options.installDir = '/usr/lib/'+ options.name;
options.service = {
  type        : 'systemd',
  name        : options.name,
  description : 'bla',
  exec        : '/usr/bin/node-simple',
  user        : 'vagrant',
  group       : 'vagrant'
};

rpm = brass.create(options);

gulp.task('clean', function () {
  return gulp.src([ rpm.buildDir, '*.tgz', '*.log' ], { read: false })
    .pipe(brass.util.stream(function (file, done) {
      this.push(file);
      rimraf(file.path, done);
    }));
});

gulp.task('setup', [ 'clean' ], rpm.setupTask());
gulp.task('source', [ 'setup' ], npm.sourceTask(pkg, rpm));

gulp.task('files', [ 'setup', 'source'], function () {
  var globs = [
    './dist/**'
  ];

  return gulp.src(globs, rpm.globOptions)
    .pipe(gulp.dest(path.join(rpm.buildRoot, options.installDir)))
    .pipe(brass.util.stream(function (file, done) {
       // if (file.relative === 'bin/node-simple') {
       //   file.attr = [ '0775', 'root', 'root' ];
       // }

       done(null, file);
    }))
    .pipe(rpm.files());
});

gulp.task('service', [ 'setup' ], npm.serviceTask(rpm));
gulp.task('binaries', [ 'files' ], npm.binariesTask(pkg, rpm));
gulp.task('spec', [ 'files', 'binaries', 'service' ], rpm.specTask());
gulp.task('build', [ 'spec' ], rpm.buildTask());

gulp.task('build-rpm', [ 'build' ], function () {
  console.log('build finished');
});
```

When I run the build-rpm task, I get a tar related error:

> [14:12:56] Using gulpfile ~\Documents\GitHub\interact\gulpfile.js
> [14:12:56] Starting 'clean'...
> [14:12:56] Finished 'clean' after 30 ms
> [14:12:56] Starting 'setup'...
> [14:12:56] Finished 'setup' after 3.08 ms
> [14:12:56] Starting 'source'...
> [14:12:56] Starting 'service'...
> [14:12:56] Finished 'service' after 32 ms
> [14:13:05] 'source' errored after 8.93 s
> [14:13:05] Error: Command failed: C:\Windows\system32\cmd.exe /s /c "tar xvzf C:
> \Users\rparker\Documents\GitHub\interact\brass_build\SOURCES\interACT-0.0.0.tgz
> --strip-components=1 -C C:\Users\rparker\Documents\GitHub\interact\brass_build\BUILD"
> tar (child): Cannot connect to C: resolve failed
> 
> gzip: stdin: unexpected end of file
> tar: Child returned status 128
> tar: Error is not recoverable: exiting now
> 
> ```
> at ChildProcess.exithandler (child_process.js:213:12)
> at emitTwo (events.js:87:13)
> at ChildProcess.emit (events.js:172:7)
> at maybeClose (internal/child_process.js:829:16)
> at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
> ```

I did a quick Google, and found posts talking about if you have a colon (:) in the tgz file path it will throw this error since its a specially treated character. So this must be due to the file path starting `C:` in the `tar` command being issued as per the stack trace.

Can you give me any assistance?

**Comment by monai** [comment]
This package was never intended to be used on MS Windows because it executes rpmbuild to do actual work. However, rpmbuild is ported to [cygwin](https://docs.fedoraproject.org/ro/Fedora_Draft_Documentation/0.1/html/RPM_Guide/ch-other-os.html#id719450) therefore theoretically it may work if you run it on cygwin environment. Anyway, recommended practice is to build package on the same system as your deployment environment, e.g. CentOS.

**Comment by parky128** [comment]
Ah ok, thanks that's very useful! We do actually use a Jenkins build system and I know rpmbuild has been installed so I'll have a go at setting up a job to run my rpm build gulp task and hopefully will get further.

**Comment by parky128** [comment]
So yes, now got an RPM being generated from our build system. Thanks again!
