### ISSUE TITLE
Date formatting with %S appends 'OURCE'

### ISSUE THREAD

**Issue by Gremash** [monai/gulp-brass#20]
I am running into this same issue on my local machine and multiple servers. I am using a spec file to set RPM properties including the RPM file name. I am generating a timestamp to add to the end of the filename. The string literal `OURCE` is being added after the seconds format specifier. None other format specifiers that I tested add the same string.

    %define build_timestamp %(date +%Y%m%d%H%M%S)
    %define _rpmfilename %%{NAME}-%{build_timestamp}.%%{ARCH}.rpm

The above produces a filename of `my-project-20170717180312OURCE.noarch.rpm`

Here is my full spec file:
```
%define build_timestamp %(date +%Y%m%d%H%M%S)
%define _topdir {{buildDir}}
%define _base   {{name}}
%define _rpmfilename %%{NAME}-%{build_timestamp}.%%{ARCH}.rpm

Summary:        {{{summary}}}
Name:           {{name}}
Group:          {{group}}
Version:        {{version}}
Release:        {{release}}
License:        {{license}}
{{#if buildarch   }}
BuildArch:      {{buildarch   }}
{{/if}}
{{#if url}}
URL:            {{url}}
{{/if}}

AutoReq:        0
AutoProv:       0
AutoReqProv:    0

%description
{{{description}}}

%files
{{{specFileList}}}
```

**Comment by monai** [comment]
Let me google that for you: http://rpm.org/user_doc/macros.html

`%S` is RPM macro that gets expanded before `date` is executed in subshell. You have to escape the macro, i.e. `%%S`.
