### ISSUE TITLE
Example for adding Gulp Build Artifacts to RPM

### ISSUE THREAD

**Issue by voor** [monai/gulp-brass#4]
I've been trying to figure out how you go about that.  Seems like since we're using npm pack it's not including any of the artifacts from gulp necessary to build or the artifacts themselves.

**Comment by voor** [comment]
I just added a new task after the setup task and before the rpm task itself.  

``` javascript
gulp.task('rpm:source-artifacts', ['rpm:setup'], function() {

  return gulp.src(path.join(process.cwd(), config.src))

  .pipe(gulp.dest(path.join(rpm.buildRoot, options.installDir, config.dest)))
    .pipe(rpm.files());
});
```

`config.dest` is the location you want the files to reside, in the above example mine is `/public/assets`

**Comment by monai** [comment]
Here's an [example](https://github.com/monai/gulp-brass/blob/develop/examples/theapp/gulpfile.js#L54) how to add files. You can have as many such tasks as you need.

I recommend at first to move source files to `rpm.buildDir_BUILD` and then gulp-source them with `rpm.globOptions` as in previous example. This convention is defined in rpmbuild's specification and it helps to avoid `path.join()` in every line as in your example.
