### ISSUE TITLE
Pre/post in/uninstall scripts ans SPEC file directives

### ISSUE THREAD

**Issue by ichyr** [monai/gulp-brass#9]
Is there a way to specify installation and uninstallation scripts that are to be included to spec file?

[Here](https://github.com/monai/gulp-brass/blob/develop/lib/rpm.js#L119) the `instance.options` is passed `butils.template`, but in that moment only `instance.options.specFileList` is specified in the RPM spec file format.

Will there be **%files** rpm spec file directive in the resulting spec file?

As I understand currently this is done by hand in the end of spec file creation?

**Comment by monai** [comment]
Regarding install/uninstall scripts see #1. In short, you should copy and modify spec file.

`instance.options` is the object passed to `brass.create(options)`. There only few keys have special purpose and you can add anything you need to it. For example, you can add install/uninstall scripts to this object and then interpolate them in modified spec template.
